"Dato 07.09.2019","Date"
"Utgave","Edition"
"Oversikt","Overview"
"Innhold","Contents"
"Profil","Profile"
"(grafisk)","(graphic)"
"(numerisk)","(numeric)"
"Egne","Custom"
"felt","fields"
"Kun psykologer eller sertifiserte brukere b<U+00F8>r tolke testresultater. Vennligst respekter de retningslinjene som gjelder for de respektive yrkesforeningene.","The test results should be interpreted by psychologists or certified users only. Please comply with applicable guidlelines from professional associations."
"Profil (grafisk)","Profile (graphic)"
"Minnesota Multiphasic Personality Inventory-2 Restructured Form <U+00B7> Standard Norske normer, totalgruppe <U+00B7> T-sk<U+00E5>re (50+10z)","Minnesota Multiphasic Personality Inventory-2 Restructured Form <U+00B7> Standard Norwegian norms, comprehensive group <U+00B7> T-scores (50+10z)"
"VRIN-r Inkonsistente svar","VRIN-r Variable Response Inconsistency"
"TRIN-r Enighetsskala","TRIN-r True Response Inconsistency"
"F-r Infrekvente svar","F-r Infrequent Responses"
"Fp-r Infrekvens psykopatologi","Fp-r Infrequent Psychopathology Responses"
"Fs Infrekvens somatikk","Fs Infrequent Somatic Responses"
"FBS-r Symptomvaliditet","FBS-r Symptom Validity"
"RBS Svartendens","RBS Response Bias Scale"
"L-r L<U+00F8>gn", "L-r Uncommon Virtues"
"K-r Korreksjon","K-r Adjustment Validity" 
"Validitetsskalaer","Validity scales" 
"Overordnede skalaer","Higher-Order Scales"
"EID Internalisering", "EID Emotional/Internalizing Dysfunction"
"THD Tankeforstyrrelser","THD Thought Dysfunction"
"BXD Eksternalisering","BXD Behavioral/Externalizing Dysfunction"
"RCd Demoralisering","RCd Demoralization" 
"RC1 Somatiske plager","RC1 Somatic Complaints"
"RC2 Lav positiv emosjonalitet","RC2 Low Positive Emotions" 
"RC3 Kynisme","RC3 Cynicism"  
"RC4 Antisosial atferd","RC4 Antisocial Behavior" 
"RC6 Forf<U+00F8>lgelsestanker","RC6 Ideas of Persecution"
"RC7 Dysfunksjonelle negative f<U+00F8>lelser","RC7 Dysfunctional Negative Emotions" 
"RC8 Avvikende opplevelser","RC8 Aberrant Experiences"
"RC9 Hypoman aktivering","RC9 Hypomanic Activation"
"Restrukturerte kliniska skalaer","Restructured Clinical Scales" 
"MLS Sykdomsf<U+00F8>lelse","MLS Malaise" 
"GIC Gatrointestinale plager","GIC Gastrointestinal Complaints" 
"HPC Hodepine","HPC Head Pain Complaints" 
"NUC Nevrologiske plager","NUC Neurological Complaints"
"COG Kognitive plager", "COG Cognitive Complaints" 
"Somatiske skalaer (skalaer for spesifikke problemer)","Somatic Scales (Specific Problem Scales)" 
"Internaliseringsskalaer (skalaer","Internalizing Scales" 
"for spesifikke problemer)","(Specific Problem Scales)"
"SUI Suicidtanker","SUI Suicidal/Death Ideation" 
"HLP Hjelpel<U+00F8>shet","HLP Helplessness/Hopelessness" 
"SFD Tviler p<U+00E5> egen mestring","SFD Self-Doubt" 
"NFC Ineffektivitet","NFC Inefficacy" 
"STW Stress og uro","STW Stress/Worry" 
"AXY Angst","AXY Anxiety"
"ANP Tilb<U+00F8>yelighet til aggresjon","ANP Anger Proneness" 
"BRF Begrensende fobier","BRF Behavior-Restricting Fears" 
"MSF Flere spesifikke fobier","MSF Multiple Specific Fears" 
"JCP Atferdsproblemer som ung","JCP Juvenile Conduct Problems" 
"SUB Rusbruk","SUB Substance Abuse" 
"AGG Aggression", "AGG Aggression" 
"ACT Aktivering","ACT Activation" 
"Eksternaliseringskalaer (skalaer","Externalizing Scales" 
"for spesifikke problemer)","(Specific Problem Scales)"
"Interpersonlige skalaer (skalaer","Internalizing Scales" 
"for spesifikke problemer)","(Specific Problem Scales)"
"FML Problemer i familie","FML Family Problems" 
"IPP Interpersonlig passivitet","IPP Interpersonal Passivity" 
"SAV Sosial unng<U+00E5>else","SAV Social Avoidance" 
"SHY Sjenanse","SHY Shyness" 
"DSF Misantropi","DSF Disaffiliativeness"
"AES Estetisk-litter<U+00E6>re interesser", "AES Aesthetic–Literary interests" 
"MEC Mekanisk-praktiske interesser", "MEC Mechanical–Physical Interests" 
"Interesseskalaer (skalaer for spesifikke problemer)","Interest Scales (Specific Problem Scales)" 
"Personlighet Psykopatologi 5","Personality Psychopathology Five Scales" 
"AGGR-r Aggresjon", "AGGR-r Aggressiveness–Revised" 
"PSYC-r Psykotisisme","PSYC-r Psychoticism–Revised"
"DISC-r Hemningsl<U+00F8>shet","DISC-r Disconstraint–Revised" 
"NEGE-r Negativ emosjonalitet/nevrotisisme","NEGE-r Negative Emotionality/Neuroticism–Revised" 
"INTR-r Introversjon lav positiv emosjonalitet","INTR-r Introversion/Low Positive Emotionality–Revised" 
"Profil (numerisk)"
"Minnesota Multiphasic Personality Inventory-2 Restructured Form <U+00B7> Standard Norske normer, totalgruppe <U+00B7> T-sk<U+00E5>re (50+10z)"
"Skala","Scale"
"R<U+00E5>sk<U+00E5>re","Raw Score"
"Skalert","Scaled"
"sk<U+00E5>re","Score"
"Internaliseringsskalaer","Internalization scales"
"(skalaer","(scales"
"for","for"
"spesifikke","specific"
"problemer)","problems)"
"Egne felt","Custom Fields"
"Felttittel","Title of Field"
"feltinnhold","Conents of Field"
"Skype, evt. telefon","Skype or telefpone number"
"Dette egne feltet er tomt","This custom field is empty"
 
